/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.Menus.view;

/**
 *
 * @author Labs-DCCO
 */
public class FrmVideoGameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmVideoGameMenu
     */
    public FrmVideoGameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuGameOn = new javax.swing.JMenu();
        menuItmAbout = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAccesories = new javax.swing.JMenu();
        mnuStorage = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuGameOn.setText("Game On");

        menuItmAbout.setText("Acerca de");
        menuItmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItmAboutActionPerformed(evt);
            }
        });
        mnuGameOn.add(menuItmAbout);

        mnuExit.setText("Salir");
        mnuGameOn.add(mnuExit);

        jMenuBar1.add(mnuGameOn);

        mnuHelp.setText("Ayuda");
        jMenuBar1.add(mnuHelp);

        mnuAccesories.setText("Accesorios");

        mnuStorage.setText("Bodega");

        jMenuItem2.setText("jMenuItem2");
        mnuStorage.add(jMenuItem2);

        jMenuItem1.setText("jMenuItem1");
        mnuStorage.add(jMenuItem1);

        jMenuItem4.setText("jMenuItem4");
        mnuStorage.add(jMenuItem4);

        jMenuItem3.setText("jMenuItem3");
        mnuStorage.add(jMenuItem3);

        mnuAccesories.add(mnuStorage);

        mnuReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuReport.setText("Reporte");
        mnuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportActionPerformed(evt);
            }
        });
        mnuAccesories.add(mnuReport);

        jMenuBar1.add(mnuAccesories);

        jMenu2.setText("jMenu2");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItmAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItmAboutActionPerformed

    private void mnuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportActionPerformed
       FrmReport freReport = new FrmReport();
       freReport.setVisible(true);
       
    }//GEN-LAST:event_mnuReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVideoGameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVideoGameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVideoGameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVideoGameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVideoGameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuItmAbout;
    private javax.swing.JMenu mnuAccesories;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuGameOn;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuReport;
    private javax.swing.JMenu mnuStorage;
    // End of variables declaration//GEN-END:variables
}
