"""empty message

Revision ID: 382bc501240e
Revises: 
Create Date: 2019-10-16 11:12:30.224929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382bc501240e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('book',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('publication_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_date'], ['author._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
